include(${libresmack_fuzz_SOURCE_DIR}/variables.cmake)

set(LIBRESMACK_FUZZ_MAIN ${LIBRESMACK_FUZZ}_main)
set(LIBRESMACK_FUZZ_MAIN_SHARED "${LIBRESMACK_FUZZ_MAIN}_shared")
set(LIBRESMACK_FUZZ_MAIN_STATIC "${LIBRESMACK_FUZZ_MAIN}_static")
set(LIBRESMACK_FUZZ_MAIN_OBJ "${LIBRESMACK_FUZZ_MAIN}_obj")
